### PR TITLE
Java 11 and Gradle 6 upgrade

### PR DESCRIPTION
**Pull request by robsonke**
Big PR but the whole java element api is changed. Works so far so good in simple microservices, will test more in next services and create a new beta.

### CODE REVIEW

**Review by robin-maxxton — APPROVED** [review]

**Comment by robsonke** [comment]
Committed small bugfix to get proper parameter descriptions

**Comment by robsonke** [comment]
Added a fix for arrays

**Comment by robsonke** [comment]
Steven, agree to merge this? We're pretty stable now. Once merged, I'll release the 2.0.0

**Review by steven166 — APPROVED** [review]
Hugh PR :) I trust you on this

**Pull request merged**
